# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.battle_extension:
        class: AppBundle\Twig\BattleExtension
        tags:
            - { name: twig.extension }

    battle.battle_manager:
        class: AppBundle\Battle\BattleManager
        arguments: ['@doctrine.orm.entity_manager']

    battle.power_manager:
        class: AppBundle\Battle\PowerManager
        arguments: ['@doctrine.orm.entity_manager']

    api_exception_subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments:
            - '%kernel.debug%'
        tags:
            - { name: kernel.event_subscriber }

    pagination_factory:
        class: AppBundle\Pagination\PaginationFactory
        arguments:
            - '@router'

    programmer_normalizer:
        class: AppBundle\Serializer\ProgrammerNormalizer
        arguments:
            - ~
            - '@programmer_name_converter'
            - '@router'
            - '@annotations.reader'
        tags:
            - { name: serializer.normalizer }

    paginated_collection_normalizer:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        arguments:
            - ~
            - '@programmer_name_converter'

    user_normalizer:
        class: AppBundle\Serializer\UserNormalizer

    programmer_name_converter:
        class: AppBundle\Serializer\ProductNameConverter

    my_serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            0:
                - '@user_normalizer'
                - '@programmer_normalizer'
                - '@paginated_collection_normalizer'
            1:
                - '@serializer.encoder.json'



